### PR TITLE
Transport errors

### PR DESCRIPTION
**Pull request by jmbillings**
Report back the actual exception when an "internal server error" occurs.

### CODE REVIEW

**Comment by alanmcgovern** [comment]
@jmbillings i think you included far more commits than you wanted to

**Comment by jmbillings** [comment]
Oops, meant to commit to our fork here...!

Sent from my HTC

----- Reply message -----

**Comment by alanmcgovern** [comment]
You might want to double check you didn't publish and private usernames/passwords/signing keys/etc. I haven't gone through the commit, but you never know ;)

**Comment by jmbillings** [comment]
Yep, thanks for the heads up!

Sent from my HTC

----- Reply message -----

**Pull request closed without merging**
